// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaWA_VD-z-81sn-pdtEjVGVggBwYj6tjk',
    appId: '1:849253157929:web:d4d3d3562b824f8d3da038',
    messagingSenderId: '849253157929',
    projectId: 'fir-7c90f',
    authDomain: 'fir-7c90f.firebaseapp.com',
    storageBucket: 'fir-7c90f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0q5SbrjiOU85b0l_t91MgCnpBkxLn60',
    appId: '1:849253157929:android:488d41940b51c7ab3da038',
    messagingSenderId: '849253157929',
    projectId: 'fir-7c90f',
    storageBucket: 'fir-7c90f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8dGW2k0QXkmh1GAvTjOMQn3VqVf2jFA',
    appId: '1:849253157929:ios:7d41db145889bfa03da038',
    messagingSenderId: '849253157929',
    projectId: 'fir-7c90f',
    storageBucket: 'fir-7c90f.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );
}
